sports_with_scores = ["Legends League Cricket", "Vijay Hazare Trophy", "Pro50 Championship",
                      "Asia Cup T20 Women", "India vs West Indies 1st ODI", "UAE vs Ireland 2nd ODI",
                      "Syed Mushtaq Ali Trophy", "South Africa Women vs Pakistan Women 3rd ODI",
                      "Big Bash Women", "Sharjah CBFS T20 League", "Desert T20", "Cricket Matches",
                      "Namibia vs Papua New Guinea - ODI",
                      "Logan Cup", "Sri Lanka vs England 1st Test", "World Cup", "Emirates D20", "Kenya T20 Cup",
                      "Big Bash", "Malaysia Quadrangular T20", "Bangladesh Premier League",
                      "Warm Up Matches", "SA20", "U19 World Cup Women", "West Indies Championship",
                      "T20 World Cup Warm Up Women", "T20 World Cup Women", "Pakistan Super League",
                      "Zimbabwe Domestic T20",
                      "ACC Challenger Cup", "WPL", "Hong Kong Quadrangular Series T20",
                      "Sri Lanka National Super League", "Dhaka Premier League", "World Cup Qualifier",
                      "Sharjah Ramadan T10",
                      "Indian Premier League", "Fairbreak T20 Women", "CC Div 1", "T10 ECI Portugal",
                      "Cool & Smooth T20", "Afghanistan One Day Cup", "JOMA Caribbean T10", "Super 50 Cup Women",
                      "St Lucia T10 Blast", "India Pondicherry T10 League", "Zimbabwe A vs Pakistan A - One Day Match",
                      "Charlotte Edwards Cup", "Nordic Cup T20", "Women's T20 Blaze",
                      "T20 Blast", "Emirates D10", "Nature Isle T10", "Namibia vs Karnataka - One Day Match",
                      "Tamil Nadu Premier League", "World Cup Qualifiers Warm Up Matches",
                      "Scotland Women vs Thailand Women - 1st Twenty20 Match", "T20 Valletta Cup",
                      "Asian Emerging Teams Cup", "Major League Cricket", "Zim Afro T10 League", "Deodhar Trophy",
                      "Minor League", "East Africa T20 Trophy", "Saurashtra Premier League",
                      "England U19 vs Australia U19", "T20 Rajasthan Premier League", "Asia Cup", "T20 KFC Max",
                      "Caribbean Premier League Women", "Gulf T20I Championship", "Richelieu Franchise T20",
                      "Malaysia T20 Tri-Nations Cup", "Australia NCL Women", "Oman D20", "Oman D10", "Ford Trophy"]
